server {
    listen       3000;
    server_name  localhost;

    # Set root directory for static files
    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # GZIP rules for faster load times on slow mobile networks
    gzip on;
    gzip_types text/css application/javascript application/json image/svg+xml;
    gzip_proxied any;

    location / {
        # Critical for PWA & Single Page Apps (React Router)
        try_files $uri $uri/ /index.html;
    }

    # Cache static files (CSS/JS/images) aggressively
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|otf|svg|mjs)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000";
    }
}